name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  # Make sure this matches the version you need

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build -v -o myapp-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: b4nd-crawler-${{ matrix.goos }}_${{ matrix.goarch }}
        path: b4nd-crawler-${{ matrix.goos }}_${{ matrix.goarch }}
